/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;

import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class NewJFrame2 extends javax.swing.JFrame {

    private NewJFrame1 ikincipencere;
    private NewJFrame ilkPencere;

    int width = 40;
    int height = 40;

    public NewJFrame2(NewJFrame1 ikiPen, NewJFrame ilkPen) {
        this.ikincipencere = ikiPen;
        this.ilkPencere = ilkPen;

        initComponents();

        this.setSize(880, 680);
        jLabel1.setVisible(false);
        jPanel1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ŞAMPİYONLAR LİGİ FİKSTÜR");
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1. HAFTA");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setOpaque(false);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("2. HAFTA");
        jLabel44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("jLabel3");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("-");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("jLabel5");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("jLabel6");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("-");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("jLabel8");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel50)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setOpaque(false);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("3. HAFTA");
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("jLabel3");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("-");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("jLabel5");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("jLabel6");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("-");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("jLabel8");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel53)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel54))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setOpaque(false);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("4. HAFTA");
        jLabel58.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("jLabel3");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("-");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("jLabel5");

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("jLabel6");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("-");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("jLabel8");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel60)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel61))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel63)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel64)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("5. HAFTA");
        jLabel65.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("jLabel3");

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("-");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("jLabel5");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("jLabel6");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("-");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("jLabel8");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel67)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel68))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel70)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel71)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67)
                    .addComponent(jLabel68))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jLabel70)
                    .addComponent(jLabel71))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setOpaque(false);

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("6. HAFTA");
        jLabel79.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("jLabel3");

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("-");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("jLabel5");

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("jLabel6");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("-");

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("jLabel8");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel79)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel81)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel82))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel84)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel85)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(jLabel81)
                    .addComponent(jLabel82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(jLabel84)
                    .addComponent(jLabel85))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 151, 850, 480);

        jPanel3.setOpaque(false);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("GRUP D FİKSTÜR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("GRUP C FİKSTÜR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("GRUP B FİKSTÜR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("GRUP A FİKSTÜR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 62, 538, 45);

        jPanel4.setOpaque(false);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("ÇIKIŞ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("GRUPLARI GÖRÜNTÜLEMEK İÇİN TIKLAYINIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 460, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 118, 150, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/dbyty.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 930, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ikincipencere.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jLabel1.setVisible(true);
        jPanel1.setVisible(true);

//grup1
        jLabel1.setText(jButton2.getText());

        ImageIcon image0 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup1_amblem.get(0) + ".png"));
        image0 = new ImageIcon(image0.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel3.setIcon(image0);
        jLabel3.setText(ilkPencere.grup1.get(0));

        ImageIcon image1 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup1_amblem.get(1) + ".png"));
        image1 = new ImageIcon(image1.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel5.setIcon(image1);
        jLabel5.setText(ilkPencere.grup1.get(1));
        jLabel5.setHorizontalTextPosition(JLabel.LEFT);

        ImageIcon image2 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup1_amblem.get(2) + ".png"));
        image2 = new ImageIcon(image2.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel6.setIcon(image2);
        jLabel6.setText(ilkPencere.grup1.get(2));

        ImageIcon image3 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup1_amblem.get(3) + ".png"));
        image3 = new ImageIcon(image3.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel8.setIcon(image3);
        jLabel8.setText(ilkPencere.grup1.get(3));
        jLabel8.setHorizontalTextPosition(JLabel.LEFT);

        jLabel45.setIcon(image0);
        jLabel45.setText(ilkPencere.grup1.get(0));
        jLabel47.setIcon(image2);
        jLabel47.setText(ilkPencere.grup1.get(2));
        jLabel47.setHorizontalTextPosition(JLabel.LEFT);
        jLabel48.setIcon(image1);
        jLabel48.setText(ilkPencere.grup1.get(1));
        jLabel50.setIcon(image3);
        jLabel50.setText(ilkPencere.grup1.get(3));
        jLabel50.setHorizontalTextPosition(JLabel.LEFT);

        jLabel52.setIcon(image0);
        jLabel52.setText(ilkPencere.grup1.get(0));
        jLabel54.setIcon(image3);
        jLabel54.setText(ilkPencere.grup1.get(3));
        jLabel54.setHorizontalTextPosition(JLabel.LEFT);
        jLabel55.setIcon(image1);
        jLabel55.setText(ilkPencere.grup1.get(1));
        jLabel57.setIcon(image2);
        jLabel57.setText(ilkPencere.grup1.get(2));
        jLabel57.setHorizontalTextPosition(JLabel.LEFT);

        jLabel59.setIcon(image1);
        jLabel59.setText(ilkPencere.grup1.get(1));
        jLabel61.setIcon(image0);
        jLabel61.setText(ilkPencere.grup1.get(0));
        jLabel61.setHorizontalTextPosition(JLabel.LEFT);
        jLabel62.setIcon(image3);
        jLabel62.setText(ilkPencere.grup1.get(3));
        jLabel64.setIcon(image2);
        jLabel64.setText(ilkPencere.grup1.get(2));
        jLabel64.setHorizontalTextPosition(JLabel.LEFT);

        jLabel66.setIcon(image2);
        jLabel66.setText(ilkPencere.grup1.get(2));
        jLabel68.setIcon(image0);
        jLabel68.setText(ilkPencere.grup1.get(0));
        jLabel68.setHorizontalTextPosition(JLabel.LEFT);
        jLabel69.setIcon(image3);
        jLabel69.setText(ilkPencere.grup1.get(3));
        jLabel71.setIcon(image1);
        jLabel71.setText(ilkPencere.grup1.get(1));
        jLabel71.setHorizontalTextPosition(JLabel.LEFT);

        jLabel80.setIcon(image3);
        jLabel80.setText(ilkPencere.grup1.get(3));
        jLabel82.setIcon(image0);
        jLabel82.setText(ilkPencere.grup1.get(0));
        jLabel82.setHorizontalTextPosition(JLabel.LEFT);
        jLabel83.setIcon(image2);
        jLabel83.setText(ilkPencere.grup1.get(2));
        jLabel85.setIcon(image1);
        jLabel85.setText(ilkPencere.grup1.get(1));
        jLabel85.setHorizontalTextPosition(JLabel.LEFT);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel1.setVisible(true);
        jPanel1.setVisible(true);
//grup2
        jLabel1.setText(jButton3.getText());

        ImageIcon image0 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup2_amblem.get(0) + ".png"));
        image0 = new ImageIcon(image0.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel3.setIcon(image0);
        jLabel3.setText(ilkPencere.grup2.get(0));

        ImageIcon image1 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup2_amblem.get(1) + ".png"));
        image1 = new ImageIcon(image1.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel5.setIcon(image1);
        jLabel5.setText(ilkPencere.grup2.get(1));
        jLabel5.setHorizontalTextPosition(JLabel.LEFT);

        ImageIcon image2 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup2_amblem.get(2) + ".png"));
        image2 = new ImageIcon(image2.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel6.setIcon(image2);
        jLabel6.setText(ilkPencere.grup2.get(2));

        ImageIcon image3 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup2_amblem.get(3) + ".png"));
        image3 = new ImageIcon(image3.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel8.setIcon(image3);
        jLabel8.setText(ilkPencere.grup2.get(3));
        jLabel8.setHorizontalTextPosition(JLabel.LEFT);

        jLabel45.setIcon(image0);
        jLabel45.setText(ilkPencere.grup2.get(0));
        jLabel47.setIcon(image2);
        jLabel47.setText(ilkPencere.grup2.get(2));
        jLabel47.setHorizontalTextPosition(JLabel.LEFT);
        jLabel48.setIcon(image1);
        jLabel48.setText(ilkPencere.grup2.get(1));
        jLabel50.setIcon(image3);
        jLabel50.setText(ilkPencere.grup2.get(3));
        jLabel50.setHorizontalTextPosition(JLabel.LEFT);

        jLabel52.setIcon(image0);
        jLabel52.setText(ilkPencere.grup2.get(0));
        jLabel54.setIcon(image3);
        jLabel54.setText(ilkPencere.grup2.get(3));
        jLabel54.setHorizontalTextPosition(JLabel.LEFT);
        jLabel55.setIcon(image1);
        jLabel55.setText(ilkPencere.grup2.get(1));
        jLabel57.setIcon(image2);
        jLabel57.setText(ilkPencere.grup2.get(2));
        jLabel57.setHorizontalTextPosition(JLabel.LEFT);

        jLabel59.setIcon(image1);
        jLabel59.setText(ilkPencere.grup2.get(1));
        jLabel61.setIcon(image0);
        jLabel61.setText(ilkPencere.grup2.get(0));
        jLabel61.setHorizontalTextPosition(JLabel.LEFT);
        jLabel62.setIcon(image3);
        jLabel62.setText(ilkPencere.grup2.get(3));
        jLabel64.setIcon(image2);
        jLabel64.setText(ilkPencere.grup2.get(2));
        jLabel64.setHorizontalTextPosition(JLabel.LEFT);

        jLabel66.setIcon(image2);
        jLabel66.setText(ilkPencere.grup2.get(2));
        jLabel68.setIcon(image0);
        jLabel68.setText(ilkPencere.grup2.get(0));
        jLabel68.setHorizontalTextPosition(JLabel.LEFT);
        jLabel69.setIcon(image3);
        jLabel69.setText(ilkPencere.grup2.get(3));
        jLabel71.setIcon(image1);
        jLabel71.setText(ilkPencere.grup2.get(1));
        jLabel71.setHorizontalTextPosition(JLabel.LEFT);

        jLabel80.setIcon(image3);
        jLabel80.setText(ilkPencere.grup2.get(3));
        jLabel82.setIcon(image0);
        jLabel82.setText(ilkPencere.grup2.get(0));
        jLabel82.setHorizontalTextPosition(JLabel.LEFT);
        jLabel83.setIcon(image2);
        jLabel83.setText(ilkPencere.grup2.get(2));
        jLabel85.setIcon(image1);
        jLabel85.setText(ilkPencere.grup2.get(1));
        jLabel85.setHorizontalTextPosition(JLabel.LEFT);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel1.setVisible(true);
        jPanel1.setVisible(true);
//grup3
        jLabel1.setText(jButton4.getText());

        ImageIcon image0 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup3_amblem.get(0) + ".png"));
        image0 = new ImageIcon(image0.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel3.setIcon(image0);
        jLabel3.setText(ilkPencere.grup3.get(0));

        ImageIcon image1 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup3_amblem.get(1) + ".png"));
        image1 = new ImageIcon(image1.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel5.setIcon(image1);
        jLabel5.setText(ilkPencere.grup3.get(1));
        jLabel5.setHorizontalTextPosition(JLabel.LEFT);

        ImageIcon image2 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup3_amblem.get(2) + ".png"));
        image2 = new ImageIcon(image2.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel6.setIcon(image2);
        jLabel6.setText(ilkPencere.grup3.get(2));

        ImageIcon image3 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup3_amblem.get(3) + ".png"));
        image3 = new ImageIcon(image3.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel8.setIcon(image3);
        jLabel8.setText(ilkPencere.grup3.get(3));
        jLabel8.setHorizontalTextPosition(JLabel.LEFT);

        jLabel45.setIcon(image0);
        jLabel45.setText(ilkPencere.grup3.get(0));
        jLabel47.setIcon(image2);
        jLabel47.setText(ilkPencere.grup3.get(2));
        jLabel47.setHorizontalTextPosition(JLabel.LEFT);
        jLabel48.setIcon(image1);
        jLabel48.setText(ilkPencere.grup3.get(1));
        jLabel50.setIcon(image3);
        jLabel50.setText(ilkPencere.grup3.get(3));
        jLabel50.setHorizontalTextPosition(JLabel.LEFT);

        jLabel52.setIcon(image0);
        jLabel52.setText(ilkPencere.grup3.get(0));
        jLabel54.setIcon(image3);
        jLabel54.setText(ilkPencere.grup3.get(3));
        jLabel54.setHorizontalTextPosition(JLabel.LEFT);
        jLabel55.setIcon(image1);
        jLabel55.setText(ilkPencere.grup3.get(1));
        jLabel57.setIcon(image2);
        jLabel57.setText(ilkPencere.grup3.get(2));
        jLabel57.setHorizontalTextPosition(JLabel.LEFT);

        jLabel59.setIcon(image1);
        jLabel59.setText(ilkPencere.grup3.get(1));
        jLabel61.setIcon(image0);
        jLabel61.setText(ilkPencere.grup3.get(0));
        jLabel61.setHorizontalTextPosition(JLabel.LEFT);
        jLabel62.setIcon(image3);
        jLabel62.setText(ilkPencere.grup3.get(3));
        jLabel64.setIcon(image2);
        jLabel64.setText(ilkPencere.grup3.get(2));
        jLabel64.setHorizontalTextPosition(JLabel.LEFT);

        jLabel66.setIcon(image2);
        jLabel66.setText(ilkPencere.grup3.get(2));
        jLabel68.setIcon(image0);
        jLabel68.setText(ilkPencere.grup3.get(0));
        jLabel68.setHorizontalTextPosition(JLabel.LEFT);
        jLabel69.setIcon(image3);
        jLabel69.setText(ilkPencere.grup3.get(3));
        jLabel71.setIcon(image1);
        jLabel71.setText(ilkPencere.grup3.get(1));
        jLabel71.setHorizontalTextPosition(JLabel.LEFT);

        jLabel80.setIcon(image3);
        jLabel80.setText(ilkPencere.grup3.get(3));
        jLabel82.setIcon(image0);
        jLabel82.setText(ilkPencere.grup3.get(0));
        jLabel82.setHorizontalTextPosition(JLabel.LEFT);
        jLabel83.setIcon(image2);
        jLabel83.setText(ilkPencere.grup3.get(2));
        jLabel85.setIcon(image1);
        jLabel85.setText(ilkPencere.grup3.get(1));
        jLabel85.setHorizontalTextPosition(JLabel.LEFT);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabel1.setVisible(true);
        jPanel1.setVisible(true);
//grup3
        jLabel1.setText(jButton5.getText());

        ImageIcon image0 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup4_amblem.get(0) + ".png"));
        image0 = new ImageIcon(image0.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel3.setIcon(image0);
        jLabel3.setText(ilkPencere.grup4.get(0));

        ImageIcon image1 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup4_amblem.get(1) + ".png"));
        image1 = new ImageIcon(image1.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel5.setIcon(image1);
        jLabel5.setText(ilkPencere.grup4.get(1));
        jLabel5.setHorizontalTextPosition(JLabel.LEFT);

        ImageIcon image2 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup4_amblem.get(2) + ".png"));
        image2 = new ImageIcon(image2.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel6.setIcon(image2);
        jLabel6.setText(ilkPencere.grup4.get(2));

        ImageIcon image3 = new ImageIcon(this.getClass().getResource("/images/" + ilkPencere.grup4_amblem.get(3) + ".png"));
        image3 = new ImageIcon(image3.getImage().getScaledInstance(width, height, BufferedImage.SCALE_SMOOTH));
        jLabel8.setIcon(image3);
        jLabel8.setText(ilkPencere.grup4.get(3));
        jLabel8.setHorizontalTextPosition(JLabel.LEFT);

        jLabel45.setIcon(image0);
        jLabel45.setText(ilkPencere.grup4.get(0));
        jLabel47.setIcon(image2);
        jLabel47.setText(ilkPencere.grup4.get(2));
        jLabel47.setHorizontalTextPosition(JLabel.LEFT);
        jLabel48.setIcon(image1);
        jLabel48.setText(ilkPencere.grup4.get(1));
        jLabel50.setIcon(image3);
        jLabel50.setText(ilkPencere.grup4.get(3));
        jLabel50.setHorizontalTextPosition(JLabel.LEFT);

        jLabel52.setIcon(image0);
        jLabel52.setText(ilkPencere.grup4.get(0));
        jLabel54.setIcon(image3);
        jLabel54.setText(ilkPencere.grup4.get(3));
        jLabel54.setHorizontalTextPosition(JLabel.LEFT);
        jLabel55.setIcon(image1);
        jLabel55.setText(ilkPencere.grup4.get(1));
        jLabel57.setIcon(image2);
        jLabel57.setText(ilkPencere.grup4.get(2));
        jLabel57.setHorizontalTextPosition(JLabel.LEFT);

        jLabel59.setIcon(image1);
        jLabel59.setText(ilkPencere.grup4.get(1));
        jLabel61.setIcon(image0);
        jLabel61.setText(ilkPencere.grup4.get(0));
        jLabel61.setHorizontalTextPosition(JLabel.LEFT);
        jLabel62.setIcon(image3);
        jLabel62.setText(ilkPencere.grup4.get(3));
        jLabel64.setIcon(image2);
        jLabel64.setText(ilkPencere.grup4.get(2));
        jLabel64.setHorizontalTextPosition(JLabel.LEFT);

        jLabel66.setIcon(image2);
        jLabel66.setText(ilkPencere.grup4.get(2));
        jLabel68.setIcon(image0);
        jLabel68.setText(ilkPencere.grup4.get(0));
        jLabel68.setHorizontalTextPosition(JLabel.LEFT);
        jLabel69.setIcon(image3);
        jLabel69.setText(ilkPencere.grup4.get(3));
        jLabel71.setIcon(image1);
        jLabel71.setText(ilkPencere.grup4.get(1));
        jLabel71.setHorizontalTextPosition(JLabel.LEFT);

        jLabel80.setIcon(image3);
        jLabel80.setText(ilkPencere.grup4.get(3));
        jLabel82.setIcon(image0);
        jLabel82.setText(ilkPencere.grup4.get(0));
        jLabel82.setHorizontalTextPosition(JLabel.LEFT);
        jLabel83.setIcon(image2);
        jLabel83.setText(ilkPencere.grup4.get(2));
        jLabel85.setIcon(image1);
        jLabel85.setText(ilkPencere.grup4.get(1));
        jLabel85.setHorizontalTextPosition(JLabel.LEFT);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
